[package]
name = "ppp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camera_capture = "0.5.0"
eframe = "0.19.0"
egui = "0.19.0"
image = "0.24.4"
imageproc = "0.23.0"
